name = "github-watcher"
main = "src/index.ts"
compatibility_date = "2025-06-20"

logpush = true

triggers = { crons = ["*/5 * * * *"] }

kv_namespaces = [
  { binding = "GITHUB_CACHE", id = "${GITHUB_CACHE_KV_ID}" }
]

[env.production]
kv_namespaces = [
  { binding = "GITHUB_CACHE", id = "${GITHUB_CACHE_KV_ID}" }
]
